on:
  push:
    branches:
      - main

  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
    
